const app = document.querySelector('#app');
const breadcrumb = document.querySelector('#breadcrumb');
const toast = document.querySelector('#toast');
let customers = [
  { phone: '254712345678', selected: true, status: 'READY' },
  { phone: '254711234567', selected: true, status: 'READY' },
  { phone: '254722345678', selected: true, status: 'READY' },
  { phone: '254701234567', selected: true, status: 'READY' },
  { phone: '254733456789', selected: true, status: 'READY' },
  { phone: '254748902134', selected: true, status: 'READY' },
  { phone: '254790123456', selected: true, status: 'READY' },
  { phone: '254768456123', selected: true, status: 'READY' }
];
let currentPage = 'dashboard';
let importReady = false;
let lastImport = null;

const money = value => `KES ${Number(value).toLocaleString('en-KE', { maximumFractionDigits: 0 })}`;
const mask = phone => `${phone.slice(0, 6)}****${phone.slice(-2)}`;
const pageNames = { dashboard: 'Overview', request: 'Request payment', sessions: 'Payment sessions', customers: 'Customers', transactions: 'Transactions', reports: 'Reports', settings: 'Settings', integration: 'PayHero integration', audit: 'Audit logs' };

function render() {
  breadcrumb.textContent = pageNames[currentPage];
  document.querySelectorAll('.nav-item').forEach(item => item.classList.toggle('active', item.dataset.page === currentPage));
  const pages = { dashboard: dashboardPage, request: requestPage, review: reviewPage, amount: amountPage, session: sessionPage, sessions: sessionsPage, customers: customersPage, transactions: transactionsPage, reports: reportsPage, settings: settingsPage, integration: integrationPage, audit: auditPage };
  app.innerHTML = pages[currentPage]();
  bindPageEvents();
}

function heading(eyebrow, title, subtitle, action = '') { return `<div class="page-heading"><div><p class="eyebrow">${eyebrow}</p><h1>${title}</h1><p>${subtitle}</p></div>${action}</div>`; }
function dashboardPage() { return `${heading('Friday, 18 September 2026', 'Good afternoon, James', 'Here is what is happening across your payment operations today.', '<button class="primary-button" data-page-action="request">＋&nbsp; Request payment</button>')}
  <div class="stat-grid"><div class="stat-card"><div class="stat-top"><span>Today\'s collections</span><span class="stat-icon">↗</span></div><h2>KES 125,500</h2><span class="trend">↑ 12.8% vs yesterday</span></div><div class="stat-card"><div class="stat-top"><span>Successful payments</span><span class="stat-icon">✓</span></div><h2>48</h2><span class="trend">↑ 8 completed today</span></div><div class="stat-card"><div class="stat-top"><span>Pending payments</span><span class="stat-icon">◷</span></div><h2>3</h2><span class="trend warn">Needs your attention</span></div><div class="stat-card"><div class="stat-top"><span>Failed payments</span><span class="stat-icon">!</span></div><h2>5</h2><span class="trend neutral">2.4% failure rate</span></div></div>
  <div class="dashboard-grid"><section class="panel chart-panel"><div class="panel-header"><h3>Collections overview</h3><a>Last 7 days⌄</a></div><div class="chart-wrap"><div class="chart-bars"><div class="bar" style="height:42%"><span>Mon</span></div><div class="bar" style="height:60%"><span>Tue</span></div><div class="bar" style="height:48%"><span>Wed</span></div><div class="bar" style="height:76%"><span>Thu</span></div><div class="bar" style="height:65%"><span>Fri</span></div><div class="bar" style="height:91%"><span>Sat</span></div><div class="bar" style="height:73%"><span>Sun</span></div></div><div class="chart-caption"><span>Total collected this week<br><strong>KES 582,500</strong></span><span class="trend">↑ 18.4%</span></div></div></section><section class="panel"><div class="panel-header"><h3>Recent activity</h3><a data-page-action="audit">View all</a></div><div class="activity-list"><div class="activity"><span class="activity-mark">✓</span><p><strong>Payment received</strong><small>254712****78 · KES 2,500 · 4 min ago</small></p></div><div class="activity"><span class="activity-mark">↗</span><p><strong>Session completed</strong><small>PS-2026-004 · 32 customers · 1 hr ago</small></p></div><div class="activity"><span class="activity-mark">＋</span><p><strong>PDF imported</strong><small>customers-sept.pdf · 118 numbers · 2 hrs ago</small></p></div><div class="activity"><span class="activity-mark">!</span><p><strong>Payment failed</strong><small>254722****19 · Timeout · 3 hrs ago</small></p></div></div></section></div>`; }

function requestPage() { return `${heading('Payment request', 'Import customer numbers', 'Upload a PDF containing numbers voluntarily provided to your business.')}
  <div class="section-card"><div id="drop-zone" class="import-drop"><div id="upload-copy"><div class="drop-icon">↑</div><h3>Drag & drop PDF here</h3><p>or</p><label class="primary-button" for="pdf-file">Choose PDF file</label><input id="pdf-file" class="file-input" type="file" accept="application/pdf,.pdf"><small class="helper">PDF only · Maximum file size 10 MB</small></div><div id="progress-state" class="progress-state"><div class="spinner"></div><p id="progress-label">Reading PDF...</p><small>We only extract Kenyan phone numbers from your file.</small><div class="progress-line"><span id="progress-fill"></span></div></div></div><div id="import-result" class="hide"></div></div>`; }
function importSummary() { const summary = lastImport || { filename: 'Imported PDF', detected: 0, valid: 0, invalid: 0, duplicates: 0 }; return `<div class="import-summary"><p class="eyebrow">PDF import complete</p><h2 style="font:600 20px 'Space Grotesk',sans-serif;margin:0 0 15px">${summary.filename}</h2><div class="summary-grid"><div class="summary-item"><strong>${summary.detected}</strong><span>Numbers detected</span></div><div class="summary-item good"><strong>${summary.valid}</strong><span>Valid Kenyan numbers</span></div><div class="summary-item bad"><strong>${summary.invalid}</strong><span>Invalid numbers</span></div><div class="summary-item"><strong>${summary.duplicates}</strong><span>Duplicates removed</span></div></div><button class="primary-button" data-page-action="review">Review numbers&nbsp; →</button></div>`; }
function reviewPage() { const visible = customers; return `${heading('Step 2 of 4', 'Review imported customers', 'Confirm the customers you want to include before setting an amount.')}
  <div class="review-layout"><section class="section-card"><div class="review-toolbar"><input class="search" id="customer-search" placeholder="⌕  Search phone number"><label class="check-all"><input id="select-all" type="checkbox" checked> Select all valid</label></div><table class="customer-table"><thead><tr><th>#</th><th>Phone number</th><th>Status</th><th></th></tr></thead><tbody id="customer-rows">${visible.map((customer, index) => `<tr data-phone="${customer.phone}"><td>${index + 1}</td><td><input type="checkbox" class="customer-check" data-index="${index}" ${customer.selected ? 'checked' : ''}> <span class="masked">${customer.displayPhone || mask(customer.phone)}</span></td><td><span class="badge ready">${customer.status}</span></td><td><button class="row-action" data-remove="${index}" aria-label="Remove customer">×</button></td></tr>`).join('')}</tbody></table><p class="helper" style="margin:15px 0 0">${customers.length} valid customers · Full phone numbers are restricted to authorized operators</p></section><section class="section-card side-summary"><h3>Authorization</h3><p>Before starting a payment session, confirm that these numbers were voluntarily provided to the business and that you are authorized to request payments from these customers.</p><label class="consent"><input id="consent" type="checkbox"><span><strong>I confirm</strong> the phone numbers in this uploaded file were voluntarily provided to the business and I am authorized to request payments from these customers.</span></label><button class="primary-button" id="continue-amount" disabled>Continue to amount&nbsp; →</button></section></div>`; }
function amountPage() { const count = customers.filter(c => c.selected).length; return `${heading('Step 3 of 4', 'Set payment amount', 'The same amount will be requested from every selected customer.')}
  <div class="review-layout"><section class="section-card"><p class="eyebrow">Payment amount</p><h2 style="font:600 22px 'Space Grotesk',sans-serif;margin:0 0 6px">How much should we request?</h2><p class="helper">Maximum per transaction: KES 150,000</p><div class="amount-input"><span>KES</span><input id="amount" type="number" min="1" max="150000" value="2500" inputmode="decimal"></div><p class="helper">Use a whole or decimal KES amount greater than zero.</p></section><section class="section-card side-summary"><h3>Session summary</h3><p>Customers selected: <strong>${count}</strong></p><p>Amount per customer: <strong id="amount-preview">KES 2,500</strong></p><p>Potential collection: <strong id="total-preview">KES ${(count * 2500).toLocaleString()}</strong></p><label class="consent"><input id="amount-confirm" type="checkbox"><span><strong>I confirm</strong> this amount and understand one payment request will be sent at a time through PayHero.</span></label><button class="primary-button" id="start-session" disabled>Start payment session&nbsp; →</button></section></div>`; }
function sessionsPage() { return `${heading('Payment sessions', 'Keep every request accountable', 'Resume an active session or review completed collections.', '<button class="primary-button" data-page-action="request">＋&nbsp; New session</button>')}<div class="session-banner"><div><p class="eyebrow" style="color:var(--lime)">Active session · PS-2026-004</p><h2>September member collections</h2><p>KES 2,500 per customer · Started today at 17:40</p></div><button class="secondary-button" data-page-action="session" style="color:#173d31">Open session&nbsp; →</button></div><section class="panel"><div class="panel-header"><h3>Recent sessions</h3><a>Export history</a></div><table class="full-table"><thead><tr><th>Session</th><th>Amount</th><th>Progress</th><th>Status</th><th>Started</th></tr></thead><tbody><tr><td><strong>PS-2026-004</strong></td><td>KES 2,500</td><td>73 / 118</td><td><span class="badge pending">RUNNING</span></td><td>Today, 17:40</td></tr><tr><td><strong>PS-2026-003</strong></td><td>KES 5,000</td><td>32 / 32</td><td><span class="badge success">COMPLETED</span></td><td>16 Sep 2026</td></tr><tr><td><strong>PS-2026-002</strong></td><td>KES 1,500</td><td>74 / 74</td><td><span class="badge success">COMPLETED</span></td><td>28 Aug 2026</td></tr></tbody></table></section>`; }
function sessionPage() { return `${heading('PS-2026-004 · Live session', 'September member collections', 'One customer is processed at a time. The next request only begins after a result is saved.')}
  <div class="session-banner"><div><p class="eyebrow" style="color:var(--lime)">Running now</p><h2>73 / 118 processed</h2><p>68 successful · 5 failed · 45 remaining</p></div><div class="session-progress"><div class="progress-label"><span>Session progress</span><strong>62%</strong></div><div class="progress-track"><span></span></div></div></div><div class="session-layout"><section class="panel current-customer"><p class="eyebrow">Current customer · #74</p><div class="current-phone">254722****45</div><div class="current-amount">Amount requested · <strong>KES 2,500</strong></div><span class="badge pending">WAITING FOR PAYMENT</span><div class="metrics"><div class="metric"><strong>68</strong><span>Successful</span></div><div class="metric"><strong>5</strong><span>Failed</span></div><div class="metric"><strong>44</strong><span>Remaining</span></div></div><div class="session-actions"><button class="secondary-button" data-action="pause">Ⅱ&nbsp; Pause session</button><button class="secondary-button danger-button" data-action="cancel">×&nbsp; Cancel</button></div></section><section class="panel"><div class="panel-header"><h3>Customer queue</h3><a>View all</a></div><div class="queue"><div class="queue-row"><span class="number">71</span><span class="queue-phone">254712****78</span><span class="queue-status status-success">SUCCESS</span></div><div class="queue-row"><span class="number">72</span><span class="queue-phone">254711****67</span><span class="queue-status status-success">SUCCESS</span></div><div class="queue-row"><span class="number">73</span><span class="queue-phone">254722****19</span><span class="queue-status status-failed">FAILED</span></div><div class="queue-row"><span class="number">74</span><span class="queue-phone">254722****45</span><span class="queue-status status-pending">PENDING</span></div><div class="queue-row"><span class="number">75</span><span class="queue-phone">254701****32</span><span class="queue-status status-waiting">WAITING</span></div></div></section></div>`; }
function customersPage() { return `${heading('Customer directory', 'Imported customers', 'Numbers stay private and are only shown to authorized operators.', '<button class="secondary-button" data-page-action="request">Import PDF</button>')}<section class="panel"><div class="panel-header"><h3>All customers · 1,248</h3><input class="search" placeholder="⌕  Search customers" style="width:200px;padding:8px"></div><table class="full-table"><thead><tr><th>Customer</th><th>Phone</th><th>Source</th><th>Last request</th><th>Status</th></tr></thead><tbody>${[['John Kamau','254712****78','customers-sept.pdf','Today','ACTIVE'],['Mary Wanjiku','254711****67','customers-sept.pdf','Today','ACTIVE'],['Peter Otieno','254722****19','members.pdf','16 Sep 2026','ACTIVE'],['Amina Hassan','254701****32','clients-august.pdf','28 Aug 2026','ACTIVE']].map(row => `<tr><td><strong>${row[0]}</strong></td><td>${row[1]}</td><td>${row[2]}</td><td>${row[3]}</td><td><span class="badge success">${row[4]}</span></td></tr>`).join('')}</tbody></table></section>`; }
function transactionsPage() { return `${heading('Transaction ledger', 'Transactions', 'Every payment attempt is recorded with its provider reference.', '<button class="secondary-button">↓&nbsp; Export CSV</button>')}<section class="panel table-panel"><table class="full-table"><thead><tr><th>Customer</th><th>Phone</th><th>Amount</th><th>Reference</th><th>Session</th><th>Status</th><th>Date</th><th>M-Pesa receipt</th></tr></thead><tbody>${[['John Kamau','254712****78','KES 2,500','PAY-001','PS-2026-004','SUCCESS','18 Sep 2026','QGH7ABC123'],['Mary Wanjiku','254711****67','KES 2,500','PAY-002','PS-2026-004','SUCCESS','18 Sep 2026','QGH7DEF456'],['Peter Otieno','254722****19','KES 2,500','PAY-003','PS-2026-004','FAILED','18 Sep 2026','—'],['Amina Hassan','254701****32','KES 2,500','PAY-004','PS-2026-004','PENDING','18 Sep 2026','—']].map(row => `<tr><td><strong>${row[0]}</strong></td><td>${row[1]}</td><td>${row[2]}</td><td>${row[3]}</td><td>${row[4]}</td><td><span class="badge ${row[5].toLowerCase()}">${row[5]}</span></td><td>${row[6]}</td><td>${row[7]}</td></tr>`).join('')}</tbody></table></section>`; }
function reportsPage() { return `${heading('Reporting', 'Collection reports', 'A clear record from uploaded source to final payment result.') }<div class="stat-grid"><div class="stat-card"><div class="stat-top"><span>Total collected</span><span class="stat-icon">↗</span></div><h2>KES 582,500</h2><span class="trend">Across 12 sessions</span></div><div class="stat-card"><div class="stat-top"><span>Successful</span><span class="stat-icon">✓</span></div><h2>286</h2><span class="trend">92.4% completion rate</span></div><div class="stat-card"><div class="stat-top"><span>Failed</span><span class="stat-icon">!</span></div><h2>18</h2><span class="trend neutral">5.8% failure rate</span></div><div class="stat-card"><div class="stat-top"><span>Skipped</span><span class="stat-icon">→</span></div><h2>6</h2><span class="trend neutral">Operator decisions</span></div></div><section class="panel"><div class="panel-header"><h3>Payment session complete · PS-2026-003</h3><button class="secondary-button">↓ Export report</button></div><div style="padding:22px;display:grid;grid-template-columns:repeat(3,1fr);gap:20px;font-size:12px"><div><span class="helper">Amount</span><p><strong>KES 5,000 per customer</strong></p><span class="helper">Total customers</span><p><strong>32</strong></p></div><div><span class="helper">Successful</span><p><strong style="color:var(--green)">29</strong></p><span class="helper">Failed</span><p><strong style="color:var(--red)">2</strong></p></div><div><span class="helper">Started</span><p><strong>16 Sep 2026 09:20</strong></p><span class="helper">Completed</span><p><strong>16 Sep 2026 10:14</strong></p></div></div></section>`; }
function settingsPage() { return `${heading('Workspace controls', 'Settings', 'Configure limits and operator safeguards for payment sessions.') }<div class="settings-grid"><section class="section-card"><p class="eyebrow">Business</p><div class="setting-row"><div><strong>Business name</strong><span>Shown in receipts and reports</span></div><strong>Jenga Kenya Ltd.</strong></div><div class="setting-row"><div><strong>Currency</strong><span>Default payment currency</span></div><strong>KES</strong></div><div class="setting-row"><div><strong>Maximum session size</strong><span>Requests per payment session</span></div><strong>250</strong></div></section><section class="section-card"><p class="eyebrow">Payment safeguards</p><div class="setting-row"><div><strong>Payment timeout</strong><span>Time before operator decision</span></div><strong>5 minutes</strong></div><div class="setting-row"><div><strong>Sequential processing</strong><span>Only one active request at a time</span></div><div class="toggle on"><i></i></div></div><div class="setting-row"><div><strong>Retry confirmation</strong><span>Require a safeguard before retry</span></div><div class="toggle on"><i></i></div></div></section></div>`; }
function integrationPage() { return `${heading('Provider connection', 'PayHero integration', 'Payment processing credentials stay server-side and are never exposed in the browser.') }<section class="section-card" style="max-width:700px"><div style="display:flex;justify-content:space-between;align-items:center"><div><p class="eyebrow">Connection status</p><h2 style="font:600 20px 'Space Grotesk',sans-serif;margin:0 0 5px">PayHero production</h2><p class="helper">Connected and ready to process payments.</p></div><span class="badge success">CONNECTED</span></div><div class="setting-row" style="margin-top:20px"><div><strong>Webhook endpoint</strong><span>Idempotent result notifications</span></div><code>/api/payhero/webhook</code></div><div class="setting-row"><div><strong>Credentials</strong><span>Managed through secure server secrets</span></div><span class="badge success">PROTECTED</span></div><button class="secondary-button" data-action="toast">Run connection check</button></section>`; }
function auditPage() { return `${heading('Traceability', 'Audit logs', 'A complete activity trail without payment credentials, PINs, or secrets.') }<section class="panel"><table class="full-table"><thead><tr><th>Event</th><th>Operator</th><th>Resource</th><th>Time</th></tr></thead><tbody>${[['PAYMENT_SUCCESS','James Kamau','PAY-002 · PS-2026-004','4 min ago'],['PAYMENT_REQUEST_SENT','System','PAY-004 · PS-2026-004','5 min ago'],['PDF_UPLOADED','James Kamau','customers-sept.pdf','2 hrs ago'],['PAYMENT_SESSION_STARTED','James Kamau','PS-2026-004','2 hrs ago'],['PAYHERO_WEBHOOK_RECEIVED','System','PAY-001 · PS-2026-004','2 hrs ago']].map(row => `<tr><td><span class="badge success">${row[0]}</span></td><td>${row[1]}</td><td>${row[2]}</td><td>${row[3]}</td></tr>`).join('')}</tbody></table></section>`; }

function bindPageEvents() {
  document.querySelectorAll('[data-page-action]').forEach(button => button.addEventListener('click', () => { const action = button.dataset.pageAction; if (action === 'review') currentPage = 'review'; else if (action === 'session') currentPage = 'session'; else currentPage = action; render(); }));
  const file = document.querySelector('#pdf-file');
  if (file) { file.addEventListener('change', () => file.files[0] && processImport(file.files[0])); const drop = document.querySelector('#drop-zone'); ['dragenter', 'dragover'].forEach(event => drop.addEventListener(event, e => { e.preventDefault(); drop.classList.add('dragging'); })); ['dragleave', 'drop'].forEach(event => drop.addEventListener(event, e => { e.preventDefault(); drop.classList.remove('dragging'); })); drop.addEventListener('drop', e => { const dropped = e.dataTransfer.files[0]; if (dropped && dropped.type === 'application/pdf') processImport(dropped); else showToast('Please choose a PDF file.'); }); }
  const consent = document.querySelector('#consent'); const continueButton = document.querySelector('#continue-amount'); if (consent) { consent.addEventListener('change', () => continueButton.disabled = !consent.checked); document.querySelector('#customer-search').addEventListener('input', filterCustomers); document.querySelector('#select-all').addEventListener('change', e => { document.querySelectorAll('.customer-check').forEach(check => { check.checked = e.target.checked; customers[check.dataset.index].selected = e.target.checked; }); }); document.querySelectorAll('.customer-check').forEach(check => check.addEventListener('change', e => customers[e.target.dataset.index].selected = e.target.checked)); document.querySelectorAll('[data-remove]').forEach(button => button.addEventListener('click', () => { customers.splice(button.dataset.remove, 1); render(); })); continueButton.addEventListener('click', () => { currentPage = 'amount'; render(); }); }
  const amount = document.querySelector('#amount'); const amountConfirm = document.querySelector('#amount-confirm'); const start = document.querySelector('#start-session'); if (amount) { const update = () => { const value = Number(amount.value); document.querySelector('#amount-preview').textContent = money(value || 0); document.querySelector('#total-preview').textContent = money(value * customers.filter(c => c.selected).length || 0); start.disabled = !(value > 0 && value <= 150000 && amountConfirm.checked); }; amount.addEventListener('input', update); amountConfirm.addEventListener('change', update); start.addEventListener('click', () => { currentPage = 'session'; render(); showToast('Payment session started. Customer 1 is ready.'); }); }
  document.querySelectorAll('[data-action="pause"]').forEach(button => button.addEventListener('click', () => showToast('Session paused. No new payment request will be sent.'))); document.querySelectorAll('[data-action="cancel"]').forEach(button => button.addEventListener('click', () => showToast('Cancellation requires confirmation in the production workflow.'))); document.querySelectorAll('[data-action="toast"]').forEach(button => button.addEventListener('click', () => showToast('PayHero connection is healthy.')));
}
function filterCustomers(event) { const query = event.target.value.toLowerCase(); document.querySelectorAll('#customer-rows tr').forEach(row => row.classList.toggle('hide', !row.dataset.phone.includes(query))); }
async function processImport(file) { if (file.type !== 'application/pdf' && !file.name.toLowerCase().endsWith('.pdf')) { showToast('Only PDF files are accepted.'); return; } document.querySelector('#upload-copy').classList.add('hide'); document.querySelector('#progress-state').classList.add('visible'); const label = document.querySelector('#progress-label'); const fill = document.querySelector('#progress-fill'); const steps = ['Reading PDF...', 'Extracting Kenyan phone numbers...', 'Validating numbers...', 'Removing duplicates...']; let index = 0; const timer = setInterval(() => { label.textContent = steps[Math.min(index, steps.length - 1)]; fill.style.width = `${Math.min((index + 1) * 25, 90)}%`; index += 1; }, 650); try { const formData = new FormData(); formData.append('pdf', file, file.name); const response = await fetch('/api/imports', { method: 'POST', body: formData }); const result = await response.json().catch(() => ({})); if (!response.ok) throw new Error(result.error || 'PDF import failed'); customers = (result.customers || []).map(customer => ({ id: customer.id, phone: customer.phone, displayPhone: customer.phone, selected: true, status: customer.status || 'READY' })); lastImport = { filename: result.filename || file.name, detected: result.detected || 0, valid: result.valid || 0, invalid: result.invalid || 0, duplicates: result.duplicates || 0 }; importReady = true; clearInterval(timer); label.textContent = 'Import complete'; fill.style.width = '100%'; setTimeout(() => { document.querySelector('#progress-state').classList.remove('visible'); document.querySelector('#import-result').classList.remove('hide'); document.querySelector('#import-result').innerHTML = importSummary(); document.querySelector('[data-page-action="review"]').addEventListener('click', () => { currentPage = 'review'; render(); }); }, 350); } catch (error) { clearInterval(timer); document.querySelector('#upload-copy').classList.remove('hide'); document.querySelector('#progress-state').classList.remove('visible'); showToast(error.message || 'Unable to import PDF'); } }
function showToast(message) { toast.textContent = message; toast.classList.add('show'); setTimeout(() => toast.classList.remove('show'), 2800); }
document.querySelectorAll('.nav-item').forEach(item => item.addEventListener('click', () => { currentPage = item.dataset.page; render(); }));
document.querySelector('.mobile-menu').addEventListener('click', () => document.querySelector('.sidebar').classList.toggle('open'));
render();